### ISSUE TITLE
New version without scrollMagic

### ISSUE THREAD

**Issue by julesbonnard** [RaphaelGuillet/cross-bitume-1#2]
Hello, 
Vu qu'au final le défilement de votre webdoc est "simple", j'ai voulu tester une version sans ScrollMagic, de façon à éviter les bugs.

Pouvez vous tester sur desktop et mobile (y compris iOS), et me dire ce que vous en pensez ? https://julesbonnard.github.io/cross-bitume/dist/index.html

Le code est dispo ici : https://github.com/julesbonnard/cross-bitume

Suivant vos retours, on peut switcher sur cette version, fusionner certaines choses, ou juste récupérer quelques tips. En particulier, je crois que j'ai trouvé comment faire définitivement disparaitre les vidéos liées sur Youtube. Il semble qu'il faut ajouter `rel: 0` aux playersVars du player Youtube (dans le js).

Bref, dites moi. De mon côté, j'ai encore quelques problèmes de chargement, mais il me semble que le tout est plus fluide.

A mercredi,

**Comment by JanMaier** [comment]
Hello,
Cette version marche plus vite sur mon mobile que celle avec Scroll Magic, c'est plus fluide et il n'y a pas ces barres blanches ou grises dans aucun des deux navigateurs. Les vidéos se chargent un peu plus vite dans Chrome que dans Firefox (sur mobile). Le seul moment où c'est un peu dur est à la fin quand nous enchaînons les deux vidéos. Mais somme toute, j'ai l'impression que c'est plus fluide.

**Comment by julesbonnard** [comment]
Ok, c'est une bonne nouvelle ! J'ai repris une bonne partie du code CSS et la structure du HTML. Les changements sont surtout dans le JS, car j'ai supprimé ScrollMagic et développé une fonction custom. Du coup, il n'y a qu'un seul panneau "fixé" en haut de la fenêtre, au lieu de plusieurs. Et c'est cela qui allège le navigateur.
@RaphaelGuillet , @ConstanceEDJ  : qu'en pensez vous ? 
Vous pouvez m'appeler si besoin, il faut qu'on s'arrange pour la transition si c'est le cas.

**Comment by JanMaier** [comment]
Il y aussi encore quelque petites fautes dans les textes <p> de l'HTML, je les corrigerai dans la version finale. Ou est-ce mieux de le faire dans ton code ici, @julesbonnard ?

**Comment by julesbonnard** [comment]
Cool, par contre un copier collé ne conviendra pas. Je propose plutôt de laisser votre code dans une branche "scrollmagic" sur votre repository, et de remplacer la branche master par votre code. 
Après, vous pourrez reprendre la main sur le html pour changer les textes et le CSS.
Par contre, je n'ai pas pu m'empecher d'ajouter quelques outils qui permettent de développer plus facilement et d'être plus compatible avec les navigateurs, que vous ne connaissez pas et que vous n'avez pas installé dans vos ordis. Donc dès que vous aurez fait les modifs, je republierai la version finale.

Ok pour que j'update la branche master ? (mettez +1 avec la petite icone smiley en haut de ce message)

**Comment by JanMaier** [comment]
:+1:
